### ISSUE TITLE
Error running getdomains.js

### ISSUE THREAD

**Issue by robrgr** [shaneturner/export-cloudflare-dns#2]
.env file contains username and api key

 export-cloudflare-dns@1.0.0 get-domains
> node src/getdomains.js "CF.env"

No envirnment ( .env ) file found. Exiting
Getting List of domains from Cloudflare
=======================================

/usr/local/Homebrew/CF_Inventory/src/getdomains.js:66
      error.response.data.errors.forEach((error) => {
                     ^

TypeError: Cannot read property 'data' of undefined
    at /usr/local/Homebrew/CF_Inventory/src/getdomains.js:66:22
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by shaneturner** [comment]
Yikes. Good catch!

Keys rotated.
