### ISSUE TITLE
Rotated Keys

### ISSUE THREAD

**Issue by robrgr** [shaneturner/export-cloudflare-dns#3]
Will an enhancement /new commit be available soon-ish?

**Comment by shaneturner** [comment]
Just tested with a dummy account and it seems to work as expected.  

If you follow the instructions in the readme, does it still throw the same errors?

**Comment by shaneturner** [comment]
Deps updated and processing of custom env files added.

**Comment by robrgr** [comment]
Hi Shane,

Yes, the tool you created works as expected and is a massive time saver.
We have approximately 400 zones to track and report on, your project is a
game saver.

Thank you,

Robert Rowsey
619.228.3344
***@***.***


[image: http://www.linkedin.com/in/robertrowsey]
<http://www.linkedin.com/in/robertrowsey>
